In [1]:
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
import sqlite3

In [3]:
conn = sqlite3.connect('local_database.db')

In [4]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)

Empty DataFrame
Columns: [name]
Index: []

In [7]:
df = pd.read_csv("C:/Users/ADMIN/Downloads/vscode/data_projects/Portfolio_proj/chhv1.csv")
df1 = pd.read_csv("C:/Users/ADMIN/Downloads/vscode/data_projects/Portfolio_proj/cperv1.csv")

In [9]:
df.to_sql('household', conn,if_exists='replace',index=False)
df1.to_sql('person', conn,if_exists='replace',index=False)

415549

In [10]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)

        name
0  household
1     person

In [11]:
pd.set_option('display.max_columns', None)
pd.read_sql_query('Select * from household',conn)

,Panel,File_Identification,Schdule,Quarter,Visit,Sector,State_Ut_Code,District_Code,NSS_Region,Stratum,Sub_Stratum,Sub_Sample,Fod_Sub_Region,FSU,Sample_Sg_Sb_No,Second_Stage_Stratum_No,Sample_Household_Number,Month_of_Survey,Response_Code,Survey_Code,Reason_for_Substitution,Household_Size,Household_Type,Religion,Social_Group,Usual_Expenditure,Imputed_Homegrown_Consumption,Imputed_Wages_Consumption,Annual_Clothing_Expenditure,Annual_Durables_Expenditure,Monthly_Consumer_Expenditure,Informant_Serial_No,Survey_Date,Total_Time_Taken,NSS_Sector_Stratum_Substr_Subsam,NSC_Sector_Stratum_Substr,Subsample_Multiplier,Contrib_Sample_Count
0,P4,CFVH4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,1,1,2,1,NaN,2,3,1,1,8500,2200,850,12000,1850,12704,1,18012024,60,1,2,1204376,4
1,P4,CFVH4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,2,1,2,1,NaN,4,1,1,1,8000,2600,880,15600,6800,13347,2,18012024,60,1,2,1204376,4
2,P4,CFVH4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,2,1,1,2,1,NaN,5,1,1,1,9000,2800,950,16000,2850,14321,2,18012024,60,1,2,1304741,4
3,P4,CFVH4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,2,2,1,2,1,NaN,6,1,1,1,11000,2600,920,18000,7500,16645,2,19012024,70,1,2,1304741,4
4,P4,CFVH4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,2,3,1,1,1,NaN,2,1,1,1,6500,1850,750,12000,2200,10283,1,19012024,50,1,2,1304741,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101952,P4,CFVH4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,2,4,1,12,1,1,NaN,2,3,1,2,8000,0,800,2500,0,9008,1,13122024,100,3,6,737070,4
101953,P4,CFVH4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,1,1,1,12,1,1,NaN,6,2,1,3,20000,0,1000,3000,0,21250,2,13122024,120,3,6,288419,4
101954,P4,CFVH4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,1,2,1,12,1,1,NaN,4,3,2,3,16000,0,4000,3000,0,20250,2,12122024,120,3,6,544791,4
101955,P4,CFVH4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,1,3,1,12,1,1,NaN,5,2,3,3,16000,0,200,3500,0,16492,2,12122024,120,3,6,528768,4
101956,P4,CFVH4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,1,4,1,12,1,1,NaN,4,2,1,2,16000,0,2000,3500,5000,18708,2,13122024,120,3,6,721047,4

In [12]:
pd.set_option('display.max_columns', None)
pd.read_sql_query('select * from person',conn)

,Panel,File_Identification,Schedule,Quarter,Visit,Sector,State_UT_Code,District_Code,NSS_Region,Stratum,Sub_Stratum,Sub_Sample,FOD_Sub_Region,FSU,Sample_Sg_Sb_No,Second_Stage_Stratum_No,Sample_Household_Number,Person_Serial_No,Relationship_To_Head,Sex,Age,Marital_Status,General_Education_Level,Technical_Education_Level,Years_Formal_Education,Current_Attendance_Status,Vocational_Training,Training_Completed_365_Days,Field_Of_Training,Duration_Of_Training,Type_Of_Training,Training_Funding_Source,Principal_Status_Code,Principal_Industry_Code,Principal_Occupation_Code,Subsidiary_Work_Engagement,Principal_Workplace_Location,Principal_Enterprise_Type,Principal_Workers_Count,Principal_Job_Contract_Type,Principal_Paid_Leave,Principal_Social_Security,Principal_Product_Usage,Subsidiary_Status_Code,Subsidiary_Industry_Code,Subsidiary_Occupation_Code,Subsidiary_Workplace_Location,Subsidiary_Enterprise_Type,Subsidiary_Workers_Count,Subsidiary_Job_Contract_Type,Subsidiary_Paid_Leave,Subsidiary_Social_Security,Subsidiary_Product_Usage,Ever_Worked_365_Days,Principal_Duration,Subsidiary_Duration,Work_Search_Efforts,Unemployment_Duration,Ever_Worked,Reason_Not_Working,Main_Reason_Principal_Status,Day7_Act1_Status_Code,Day7_Act1_Industry_Code,Day7_Act1_Hours,Day7_Act1_Wage,Day7_Act2_Status_Code,Day7_Act2_Industry_Code,Day7_Act2_Hours,Day7_Act2_Wage,Day7_Total_Hours,Day7_Additional_Work_Hours,Day6_Act1_Status_Code,Day6_Act1_Industry_Code,Day6_Act1_Hours,Day6_Act1_Wage,Day6_Act2_Status_Code,Day6_Act2_Industry_Code,Day6_Act2_Hours,Day6_Act2_Wage,Day6_Total_Hours,Day6_Additional_Work_Hours,Day5_Act1_Status_Code,Day5_Act1_Industry_Code,Day5_Act1_Hours,Day5_Act1_Wage,Day5_Act2_Status_Code,Day5_Act2_Industry_Code,Day5_Act2_Hours,Day5_Act2_Wage,Day5_Total_Hours,Day5_Additional_Work_Hours,Day4_Act1_Status_Code,Day4_Act1_Industry_Code,Day4_Act1_Hours,Day4_Act1_Wage,Day4_Act2_Status_Code,Day4_Act2_Industry_Code,Day4_Act2_Hours,Day4_Act2_Wage,Day4_Total_Hours,Day4_Additional_Work_Hours,Day3_Act1_Status_Code,Day3_Act1_Industry_Code,Day3_Act1_Hours,Day3_Act1_Wage,Day3_Act2_Status_Code,Day3_Act2_Industry_Code,Day3_Act2_Hours,Day3_Act2_Wage,Day3_Total_Hours,Day3_Additional_Work_Hours,Day2_Act1_Status_Code,Day2_Act1_Industry_Code,Day2_Act1_Hours,Day2_Act1_Wage,Day2_Act2_Status_Code,Day2_Act2_Industry_Code,Day2_Act2_Hours,Day2_Act2_Wage,Day2_Total_Hours,Day2_Additional_Work_Hours,Day1_Act1_Status_Code,Day1_Act1_Industry_Code,Day1_Act1_Hours,Day1_Act1_Wage,Day1_Act2_Status_Code,Day1_Act2_Industry_Code,Day1_Act2_Hours,Day1_Act2_Wage,Day1_Total_Hours,Day1_Additional_Work_Hours,CWS_Status_Code,CWS_Industry_Code,CWS_Occupation_Code,CWS_Earnings_Salaried,CWS_Earnings_SelfEmployed,Ns_Count_Sector_Stratum_Substratum_Subsample,Ns_Count_Sector_Stratum_Substratum,Subsample_Multiplier,State_Sector_Stratum_Substra
0,P4,CFVP4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,1,1,1,1,35,2,8,1,10,NaN,6.0,NaN,NaN,NaN,NaN,NaN,31,84119.0,335.0,1,16.0,5.0,3.0,4.0,1.0,8.0,NaN,11.0,1286.0,611.0,NaN,1.0,1.0,NaN,NaN,NaN,3.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,31,84.0,8,0,NaN,NaN,0,0,8,0,31,84.0,8,0,11.0,1.0,2,0,10,0,31,84.0,8,0,11.0,1.0,2,0,10,0,72,84.0,8,0,11.0,1.0,8,0,8,0,31,84.0,8,0,11.0,1.0,2,0,10,0,31,84.0,8,0,NaN,NaN,0,0,8,0,31,84.0,8,0,11.0,1.0,2,0,10,0,31,84.0,335.0,9500,0,1,2,1204376,4
1,P4,CFVP4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,1,2,2,2,33,2,8,1,10,NaN,6.0,NaN,NaN,NaN,NaN,NaN,21,1286.0,611.0,1,NaN,1.0,1.0,NaN,NaN,NaN,3.0,41.0,42204.0,931.0,16.0,5.0,4.0,1.0,2.0,8.0,NaN,1.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,21,1.0,8,0,NaN,NaN,0,0,8,0,21,1.0,6,0,NaN,NaN,0,0,6,0,21,1.0,7,0,NaN,NaN,0,0,7,0,21,1.0,5,0,NaN,NaN,0,0,5,0,21,1.0,7,0,NaN,NaN,0,0,7,0,21,1.0,8,0,NaN,NaN,0,0,8,0,21,1.0,6,0,NaN,NaN,0,0,6,0,21,1.0,611.0,0,0,1,2,1204376,4
2,P4,CFVP4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,2,1,1,1,36,2,10,1,12,NaN,6.0,NaN,NaN,NaN,NaN,NaN,11,1286.0,611.0,1,NaN,1.0,1.0,NaN,NaN,NaN,3.0,11.0,49219.0,832.0,19.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,11,1.0,8,0,NaN,NaN,0,0,8,0,11,1.0,7,0,NaN,NaN,0,0,7,0,62,1.0,7,0,11.0,49.0,8,0,8,0,11,1.0,6,0,11.0,49.0,4,0,10,0,11,1.0,8,0,NaN,NaN,0,0,8,0,11,1.0,6,0,11.0,49.0,4,0,10,0,11,1.0,9,0,NaN,NaN,0,0,9,0,11,1.0,611.0,0,16500,1,2,1204376,4
3,P4,CFVP4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,2,2,2,2,34,2,10,1,12,NaN,6.0,NaN,NaN,NaN,NaN,NaN,31,86904.0,531.0,1,16.0,5.0,4.0,4.0,1.0,5.0,NaN,21.0,1286.0,611.0,NaN,1.0,1.0,NaN,NaN,NaN,3.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,31,86.0,8,0,NaN,NaN,0,0,8,0,31,86.0,8,0,NaN,NaN,0,0,8,0,31,86.0,8,0,NaN,NaN,0,0,8,0,72,86.0,8,0,21.0,1.0,8,0,8,0,31,86.0,8,0,21.0,1.0,2,0,10,0,31,86.0,8,0,NaN,NaN,0,0,8,0,31,86.0,8,0,NaN,NaN,0,0,8,0,31,86.0,531.0,11500,0,1,2,1204376,4
4,P4,CFVP4,104,Q3,V1,1,28,20,281,1,1,1,2822,12121,1,1,2,3,5,2,12,1,6,1,6,25.0,6.0,NaN,NaN,NaN,NaN,NaN,91,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,4.0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,NaN,0,0,1,2,1204376,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415544,P4,CFVP4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,2,2,1,4,5,2,4,1,1,1,0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,99,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,0,0,NaN,NaN,0,0,0,0,99,NaN,NaN,0,0,3,6,1281861,4
415545,P4,CFVP4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,2,2,1,5,7,2,59,3,1,1,0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,94,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,8.0,3.0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,0,0,NaN,NaN,0,0,0,0,94,NaN,NaN,0,0,3,6,1281861,4
415546,P4,CFVP4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,2,3,1,1,1,1,24,1,8,1,11,12.0,4.0,NaN,NaN,NaN,NaN,NaN,31,47211.0,522.0,2,26.0,1.0,1.0,1.0,1.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,31,47.0,8,0,NaN,NaN,0,0,8,0,31,47.0,8,0,NaN,NaN,0,0,8,0,31,47.0,8,0,NaN,NaN,0,0,8,0,31,47.0,8,0,NaN,NaN,0,0,8,0,72,47.0,8,0,NaN,NaN,0,0,0,0,31,47.0,8,0,NaN,NaN,0,0,8,0,31,47.0,8,0,NaN,NaN,0,0,8,0,31,47.0,522.0,12000,0,3,6,961396,4
415547,P4,CFVP4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,2,4,1,1,1,1,55,2,7,1,9,NaN,4.0,NaN,NaN,NaN,NaN,NaN,51,41001.0,711.0,2,28.0,19.0,1.0,1.0,2.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,51,41.0,8,1000,NaN,NaN,0,0,8,0,51,41.0,8,1000,NaN,NaN,0,0,8,0,51,41.0,8,1000,NaN,NaN,0,0,8,0,81,NaN,0,0,NaN,NaN,0,0,0,0,81,NaN,0,0,NaN,NaN,0,0,0,0,81,NaN,0,0,NaN,NaN,0,0,0,0,51,41.0,8,1000,NaN,NaN,0,0,8,0,51,41.0,711.0,0,0,3,6,737070,4
415548,P4,CFVP4,104,Q6,V1,2,34,2,341,3,3,2,3323,20629,2,4,1,2,2,2,55,2,6,1,5,NaN,6.0,NaN,NaN,NaN,NaN,NaN,92,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,7.0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,NaN,0,0,3,6,737070,4

 ## IDENTIFY JOIN KEYS (CRITICAL)
- Purpose :- Confirm how household and person connect.

-  Shared columns (from your data):
   - FSU
   - Sample_Sg_Sb_No
   - Second_Stage_Stratum_No
   - Sample_Household_Number

- Conclusion
  - These four columns together uniquely identify a household.
  - This is our natural composite key.

In [25]:
pd.read_sql("""
SELECT 
    FSU, Sample_Sg_Sb_No, Second_Stage_Stratum_No, Sample_Household_Number
FROM household
LIMIT 5;
""", conn)

     FSU  Sample_Sg_Sb_No  Second_Stage_Stratum_No  Sample_Household_Number
0  12121                1                        1                        1
1  12121                1                        1                        2
2  12121                1                        2                        1
3  12121                1                        2                        2
4  12121                1                        2                        3

In [26]:
pd.read_sql("""
SELECT 
    FSU, Sample_Sg_Sb_No, Second_Stage_Stratum_No, Sample_Household_Number
FROM person
LIMIT 5;
""", conn)

     FSU  Sample_Sg_Sb_No  Second_Stage_Stratum_No  Sample_Household_Number
0  12121                1                        1                        1
1  12121                1                        1                        1
2  12121                1                        1                        2
3  12121                1                        1                        2
4  12121                1                        1                        2

Conclusion:
- The composite key (FSU, Sample_Sg_Sb_No, Second_Stage_Stratum_No, Sample_Household_Number) uniquely identifies households.
- The person table exhibits a one-to-many relationship with households, confirming that person-level data must be aggregated before joining to household data to avoid duplication and biased analysis.

- Required for foreign key modeling later

In [ ]:
pd.read_sql("""
SELECT
    FSU,
    Sample_Sg_Sb_No,
    Second_Stage_Stratum_No,
    Sample_Household_Number,
    COUNT(*) AS persons_per_household
FROM person
GROUP BY
    FSU,
    Sample_Sg_Sb_No,
    Second_Stage_Stratum_No,
    Sample_Household_Number
HAVING COUNT(*) > 1
LIMIT 10;
""", conn)

,FSU,Sample_Sg_Sb_No,Second_Stage_Stratum_No,Sample_Household_Number,persons_per_household
0,10001,1,1,1,5
1,10001,1,1,2,5
2,10001,1,2,1,5
3,10001,1,2,2,5
4,10001,1,2,3,6
5,10001,1,2,4,4
6,10001,1,3,1,3
7,10001,1,3,2,4
8,10002,1,1,1,4
9,10002,1,2,2,3

Conclusion:
- Person-level data shows multiple individuals per household, with household sizes ranging from 3 to 6 persons. This confirms a one-to-many relationship between households and persons, reinforcing the need to aggregate person-level attributes to the household level prior to any joins to avoid duplication and biased estimates.

##  RURAL vs URBAN DISTRIBUTION
- Purpose
  - This drives multiple employment comparisons between Rural and Urban .

- Insight
  - Enables rural vs urban employment, income, underemployment analysis
The household sample is well distributed across rural and urban sectors, with substantial representation in both groups. This validates the use of sector as a primary segmentation variable for employment, income, and consumption comparisons, while highlighting the need to apply survey weights for population-level inference.

In [ ]:
("""
SELECT
    Sector,
    COUNT(*) AS household_count
FROM household
GROUP BY Sector;
""", conn)

   Sector  household_count
0       1            55846
1       2            46111

## HOUSEHOLD ECONOMIC SPREAD
- Purpose
  - Understand inequality and background effects.

- Insight
  - Large spread → strong economic inequality
  - Will influence employment outcomes
 - Inequality likely affects employment outcomes

In [18]:
df_household = pd.read_sql("SELECT Monthly_Consumer_Expenditure FROM household", conn)

df_household.agg(
    min_mce=('Monthly_Consumer_Expenditure', 'min'),
    max_mce=('Monthly_Consumer_Expenditure', 'max'),
    avg_mce=('Monthly_Consumer_Expenditure', 'mean'),
    median_mce=('Monthly_Consumer_Expenditure', 'median')
)

            Monthly_Consumer_Expenditure
min_mce                       450.000000
max_mce                    175625.000000
avg_mce                     13567.084016
median_mce                  11642.000000

## EMPLOYMENT STATUS DISTRIBUTION (PERSON)
- Purpose
  - Understand workforce composition.
- Insight
  - Multiple employment categories
  - CWS_Status_Code best reflects current weekly status

In [30]:
pd.read_sql("""
SELECT
    CWS_Status_Code,
    COUNT(*) AS person_count
FROM person
GROUP BY CWS_Status_Code
ORDER BY person_count DESC;
""", conn)

    CWS_Status_Code  person_count
0                91        105362
1                11         62676
2                92         58576
3                31         45687
4                99         29634
5                51         26022
6                21         23975
7                93         18014
8                94         16125
9                81          8809
10               12          5871
11               97          4279
12               95          4018
13               62          1891
14               82          1399
15               42          1145
16               72           983
17               98           410
18               61           272
19               41           239
20               71           162

## AGE DISTRIBUTION (Youth vs Adult distribution)

In [23]:
pd.read_sql("""
SELECT
    MIN(Age) AS min_age,
    MAX(Age) AS max_age,
    AVG(Age) AS avg_age
FROM person
where age between 15 AND 64
""", conn)

   min_age  max_age   avg_age
0       15       64  35.91278

In [24]:
pd.read_sql("""SELECT
    CASE
        WHEN Age BETWEEN 15 AND 24 THEN 'Youth (15–24)'
        WHEN Age BETWEEN 25 AND 64 THEN 'Adult (25–64)'
        ELSE 'Outside Working Age'
    END AS age_group,
    COUNT(*) AS person_count
FROM person
GROUP BY age_group
ORDER BY person_count DESC;""",conn)

             age_group  person_count
0        Adult (25–64)        213195
1  Outside Working Age        127209
2        Youth (15–24)         75145

The population is predominantly of working age, with adults (25–64) forming the largest group, while youth (15–24) constitute a substantial and analytically meaningful segment. This distribution supports separate youth-focused labour-market analysis and reinforces the need to exclude non-working-age individuals from employment outcome calculations.

## WEEKLY WORKING HOURS (JOB QUALITY)
- Purpose
  - Identify underemployment.

- Insight
  - Low totals → disguised unemployment
  - Wide variance → informal sector dominance

In [25]:
pd.read_sql("""
SELECT
    AVG(
        IFNULL(Day1_Total_Hours,0) +
        IFNULL(Day2_Total_Hours,0) +
        IFNULL(Day3_Total_Hours,0) +
        IFNULL(Day4_Total_Hours,0) +
        IFNULL(Day5_Total_Hours,0) +
        IFNULL(Day6_Total_Hours,0) +
        IFNULL(Day7_Total_Hours,0)
    ) AS avg_weekly_hours_employed
FROM person
WHERE
    Age BETWEEN 15 AND 64
    AND CWS_Status_Code IN (11,12,21,31,41,51,61,71,81);
""",conn)

   avg_weekly_hours_employed
0                  41.426936

In [26]:
pd.read_sql("""
SELECT
    CASE
        WHEN Age BETWEEN 15 AND 24 THEN 'Youth (15–24)'
        ELSE 'Adult (25–64)'
    END AS age_group,
    CASE
        WHEN (
            IFNULL(Day1_Total_Hours,0) +
            IFNULL(Day2_Total_Hours,0) +
            IFNULL(Day3_Total_Hours,0) +
            IFNULL(Day4_Total_Hours,0) +
            IFNULL(Day5_Total_Hours,0) +
            IFNULL(Day6_Total_Hours,0) +
            IFNULL(Day7_Total_Hours,0)
        ) < 35 THEN 'Underemployed'
        ELSE 'Adequately Employed'
    END AS job_quality,
    COUNT(*) AS person_count
FROM person
WHERE
    Age BETWEEN 15 AND 64
    AND CWS_Status_Code IN (11,12,21,31,41,51,61,71,81)
GROUP BY age_group, job_quality
ORDER BY age_group, person_count DESC;
""",conn)

       age_group          job_quality  person_count
0  Adult (25–64)  Adequately Employed        105294
1  Adult (25–64)        Underemployed         38226
2  Youth (15–24)  Adequately Employed         13260
3  Youth (15–24)        Underemployed         10081

## EARNINGS AVAILABILITY CHECK

In [33]:
pd.read_sql("""
SELECT
    SUM(CASE WHEN CWS_Earnings_Salaried IS NULL THEN 1 ELSE 0 END) AS missing_salaried,
    SUM(CASE WHEN CWS_Earnings_SelfEmployed IS NULL THEN 1 ELSE 0 END) AS missing_self_employed
FROM person;
""", conn)

   missing_salaried  missing_self_employed
0                 0                      0

In [27]:
pd.read_sql("""SELECT
    SUM(CASE WHEN CWS_Earnings_Salaried > 0 THEN 1 ELSE 0 END) AS salaried_positive,
    SUM(CASE WHEN CWS_Earnings_SelfEmployed > 0 THEN 1 ELSE 0 END) AS self_employed_positive
FROM person
WHERE
    Age BETWEEN 15 AND 64
    AND CWS_Status_Code IN (11,12,21,31,41,51,61,71,81);
""",conn)

   salaried_positive  self_employed_positive
0              45282                   63813

Earnings variables are fully populated with no missing values. However, positive earnings are observed only among relevant employed subgroups, indicating that zero values represent structural non-applicability rather than missing income. Earnings analysis must therefore be restricted to individuals with positive earnings in the corresponding employment category.

## SUMMARY
We establish a clear and reliable foundation for analysis:

- ✔ The data grain is explicitly validated: households and persons follow a strict one-to-many hierarchy
- ✔ Composite join keys correctly identify households and prevent duplication errors
- ✔ Person-level data is confirmed to require aggregation before household joins
- ✔ Current Weekly Status (CWS) is identified as the most appropriate indicator of employment
- ✔ The working-age population and youth segment are clearly defined and adequately represented
- ✔ Household consumption shows strong economic heterogeneity, indicating inequality
- ✔ Rural–urban segmentation is well balanced and suitable for comparative analysis
- ✔ Weekly working hours reveal underemployment risk when restricted to employed individuals
- ✔ Earnings variables are technically complete, with zero values reflecting structural non-applicability rather than missing data

# Data Modeling

* Table Roles
* (Table)household -- 	(Purpose) Household demographics & economic background
* (table)person ---	(Purpose) Individual employment, education, work & earnings

## CREATE HOUSEHOLD DIMENSION TABLE
- Purpose :- One row per household
- Replace complex composite keys with household_id

- Why this design?
  - household_id → surrogate primary key
  - Natural keys retained → audit & debugging
  - Economic variables centralized → shared context

In [41]:
cursor = conn.cursor()

cursor.execute("""
DROP TABLE IF EXISTS household_dim;
""")

conn.commit()

In [42]:
cursor.execute("""CREATE TABLE household_dim AS
SELECT
    ROW_NUMBER() OVER (
        ORDER BY 
            FSU,
            Sample_Sg_Sb_No,
            Second_Stage_Stratum_No,
            Sample_Household_Number
    ) AS household_id,
               
    -- Survey info
    Panel,
    Quarter,
    Visit,
    Survey_Date,

    -- Natural household keys
    FSU,
    Sample_Sg_Sb_No,
    Second_Stage_Stratum_No,
    Sample_Household_Number,

    -- Geography
    Sector,
    State_Ut_Code,
    District_Code,
    NSS_Region,

    -- Household profile
    Household_Size,
    Household_Type,
    Religion,
    Social_Group,

    -- Economic indicators (standardized)
    Usual_Expenditure,
    Monthly_Consumer_Expenditure,
    Annual_Clothing_Expenditure / 12.0 AS Monthly_Clothing_Expenditure,
    Annual_Durables_Expenditure / 12.0 AS Monthly_Durables_Expenditure

FROM household;
""")
conn.commit()

In [43]:
pd.read_sql(" select * from household_dim",conn)

,household_id,Panel,Quarter,Visit,Survey_Date,FSU,Sample_Sg_Sb_No,Second_Stage_Stratum_No,Sample_Household_Number,Sector,State_Ut_Code,District_Code,NSS_Region,Household_Size,Household_Type,Religion,Social_Group,Usual_Expenditure,Monthly_Consumer_Expenditure,Monthly_Clothing_Expenditure,Monthly_Durables_Expenditure
0,1,P4,Q6,V1,21112024,10001,1,1,1,1,29,19,293,5,1,1,3,14500,19833,1041.666667,291.666667
1,2,P4,Q6,V1,21112024,10001,1,1,2,1,29,19,293,5,1,1,3,17500,21346,1041.666667,104.166667
2,3,P4,Q6,V1,21112024,10001,1,2,1,1,29,19,293,5,1,1,3,9850,12982,875.000000,106.666667
3,4,P4,Q6,V1,22112024,10001,1,2,2,1,29,19,293,5,4,1,3,12650,15451,875.000000,145.833333
4,5,P4,Q6,V1,22112024,10001,1,2,3,1,29,19,293,6,4,1,3,14750,19096,933.333333,312.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101952,101953,P4,Q4,V1,28052024,26235,1,2,2,2,28,3,281,2,9,1,3,13500,14042,541.666667,0.000000
101953,101954,P4,Q4,V1,28052024,26235,1,3,1,2,28,3,281,1,1,1,3,13500,16958,833.333333,2625.000000
101954,101955,P4,Q4,V1,28052024,26235,1,3,2,2,28,3,281,1,9,1,3,14000,14708,708.333333,0.000000
101955,101956,P4,Q4,V1,31052024,26235,1,4,1,2,28,3,281,1,9,1,3,12250,14525,483.333333,1791.666667
101956,101957,P4,Q4,V1,28052024,26235,1,4,2,2,28,3,281,2,2,1,3,20000,21667,1666.666667,0.000000

In [44]:
pd.read_sql("""
SELECT COUNT(*) AS households_modelled
FROM household_dim;
""", conn)

   households_modelled
0               101957

In [45]:
pd.read_sql_query(" select monthly_Clothing_Expenditure from household_dim",conn)

        Monthly_Clothing_Expenditure
0                        1041.666667
1                        1041.666667
2                         875.000000
3                         875.000000
4                         933.333333
...                              ...
101952                    541.666667
101953                    833.333333
101954                    708.333333
101955                    483.333333
101956                   1666.666667

[101957 rows x 1 columns]

## CREATE PERSON FACT TABLE (WITH FK)

- Purpose :- One row per person , Link every person to exactly one household


- Why this design?
  - person_id → unique person key
  - household_id → foreign key
  - Separates context (household) from outcomes (person)
  - This is textbook star-schema thinking.

In [46]:
cursor.execute("""
CREATE TABLE person_fact AS
SELECT
     ROW_NUMBER() OVER (
        ORDER BY
            h.household_id,
            p.Person_Serial_No
    ) AS person_id,

    -- Foreign key
    h.household_id,

    -- Person identifiers
    p.Person_Serial_No,
    p.Relationship_To_Head,

    -- Demographics
    p.Sex,
    p.Age,
    p.Marital_Status,

    -- Education & skills
    p.General_Education_Level,
    p.Technical_Education_Level,
    p.Years_Formal_Education,
    p.Vocational_Training,

    -- Employment status
    p.Principal_Status_Code,
    p.Subsidiary_Status_Code,
    p.CWS_Status_Code,

    -- Industry & occupation
    p.Principal_Industry_Code,
    p.Principal_Occupation_Code,
    p.Subsidiary_Industry_Code,
    p.Subsidiary_Occupation_Code,

    -- Earnings
    p.CWS_Earnings_Salaried,
    p.CWS_Earnings_SelfEmployed,

    -- Weekly work (job quality)
    (
        IFNULL(p.Day1_Total_Hours,0) +
        IFNULL(p.Day2_Total_Hours,0) +
        IFNULL(p.Day3_Total_Hours,0) +
        IFNULL(p.Day4_Total_Hours,0) +
        IFNULL(p.Day5_Total_Hours,0) +
        IFNULL(p.Day6_Total_Hours,0) +
        IFNULL(p.Day7_Total_Hours,0)
    ) AS Weekly_Hours_Worked,

    -- Survey time dimensions
    p.Quarter,
    p.Visit

FROM person p
JOIN household_dim h
ON p.FSU = h.FSU
AND p.Sample_Sg_Sb_No = h.Sample_Sg_Sb_No
AND p.Second_Stage_Stratum_No = h.Second_Stage_Stratum_No
AND p.Sample_Household_Number = h.Sample_Household_Number;
""",)
conn.commit()

In [47]:
pd.read_sql("""
SELECT
    COUNT(*) AS persons_modelled
FROM person_fact;
""", conn)

   persons_modelled
0            415549

In [48]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)

            name
0      household
1         person
2  household_dim
3    person_fact

## ADD PRIMARY & FOREIGN KEYS (LOGICAL)

In [49]:
conn.execute("PRAGMA foreign_keys = ON;")
conn.commit()

In [50]:
conn.execute("""
CREATE UNIQUE INDEX idx_household_pk
ON household_dim(household_id);
""")
conn.commit()

In [51]:

conn.execute("""
CREATE UNIQUE INDEX idx_person_pk
ON person_fact(person_id);
""")
conn.commit()

In [52]:
conn.execute("""
CREATE INDEX idx_person_household_fk
ON person_fact(household_id);
""")
conn.commit()

In [63]:
pd.read_sql("PRAGMA table_info(person_fact);", conn)

    cid                        name  type  notnull dflt_value  pk
0     0                   person_id              0       None   0
1     1                household_id              0       None   0
2     2            Person_Serial_No   INT        0       None   0
3     3        Relationship_To_Head   INT        0       None   0
4     4                         Sex   INT        0       None   0
5     5                         Age   INT        0       None   0
6     6              Marital_Status   INT        0       None   0
7     7     General_Education_Level   INT        0       None   0
8     8   Technical_Education_Level   INT        0       None   0
9     9      Years_Formal_Education   INT        0       None   0
10   10         Vocational_Training  REAL        0       None   0
11   11       Principal_Status_Code   INT        0       None   0
12   12      Subsidiary_Status_Code  REAL        0       None   0
13   13             CWS_Status_Code   INT        0       None   0
14   14     Principal_Industry_Code  REAL        0       None   0
15   15   Principal_Occupation_Code  REAL        0       None   0
16   16    Subsidiary_Industry_Code  REAL        0       None   0
17   17  Subsidiary_Occupation_Code  REAL        0       None   0
18   18       CWS_Earnings_Salaried   INT        0       None   0
19   19   CWS_Earnings_SelfEmployed   INT        0       None   0
20   20         Weekly_Hours_Worked              0       None   0
21   21                     Quarter  TEXT        0       None   0
22   22                       Visit  TEXT        0       None   0

In [59]:
pd.read_sql_query(" Select * from person_fact",conn)

,person_id,household_id,Person_Serial_No,Relationship_To_Head,Sex,Age,Marital_Status,General_Education_Level,Technical_Education_Level,Years_Formal_Education,Vocational_Training,Principal_Status_Code,Subsidiary_Status_Code,CWS_Status_Code,Principal_Industry_Code,Principal_Occupation_Code,Subsidiary_Industry_Code,Subsidiary_Occupation_Code,CWS_Earnings_Salaried,CWS_Earnings_SelfEmployed,Weekly_Hours_Worked,Quarter,Visit
0,1,1,1,1,1,42,2,7,1,8,6.0,11,51.0,11,1140.0,611.0,1611.0,921.0,0,18250,47,Q6,V1
1,2,1,2,2,2,38,2,7,1,8,6.0,11,21.0,11,1412.0,612.0,1140.0,611.0,0,4850,48,Q6,V1
2,3,1,3,5,2,18,1,10,1,12,6.0,91,NaN,91,NaN,NaN,NaN,NaN,0,0,0,Q6,V1
3,4,1,4,5,2,16,1,8,1,11,6.0,91,NaN,91,NaN,NaN,NaN,NaN,0,0,0,Q6,V1
4,5,1,5,7,2,70,3,1,1,0,NaN,93,NaN,93,NaN,NaN,NaN,NaN,0,0,0,Q6,V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415544,415545,101954,1,1,1,70,3,13,16,17,NaN,94,11.0,11,NaN,NaN,69100.0,261.0,0,25000,32,Q4,V1
415545,415546,101955,1,1,2,70,3,12,1,15,NaN,94,NaN,94,NaN,NaN,NaN,NaN,0,0,0,Q4,V1
415546,415547,101956,1,1,1,68,3,10,1,12,NaN,94,NaN,94,NaN,NaN,NaN,NaN,0,0,0,Q4,V1
415547,415548,101957,1,1,1,58,2,13,1,17,1.0,31,NaN,31,49110.0,313.0,NaN,NaN,52500,0,58,Q4,V1
415548,415549,101957,2,2,2,57,2,13,1,16,6.0,31,NaN,31,85211.0,233.0,NaN,NaN,25000,0,62,Q4,V1

In [60]:
pd.read_sql(
    "SELECT Weekly_Hours_Worked FROM person_fact LIMIT 5;",
    conn
)

   Weekly_Hours_Worked
0                   47
1                   48
2                    0
3                    0
4                    0

## Underemployment flag (technical)

In [64]:
cursor.execute("""
ALTER TABLE person_fact
ADD COLUMN underemployed_flag INTEGER;
""")

conn.commit()

In [65]:
cursor.execute("""
UPDATE person_fact
SET underemployed_flag =
    CASE
        WHEN Age BETWEEN 15 AND 64
         AND CWS_Status_Code IN (11,12,21,31,41,51,61,71,81)
         AND weekly_hours_worked < 35
        THEN 1
        ELSE 0
    END;
""")

conn.commit()

In [67]:
pd.read_sql(
    "SELECT underemployed_flag FROM person_fact LIMIT 10;",
    conn
)

   underemployed_flag
0                   0
1                   0
2                   0
3                   0
4                   0
5                   0
6                   0
7                   0
8                   0
9                   0

## CREATE THE FINAL ANALYTICAL FACT TABLE

In [70]:
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE employment_analytical_fact AS
SELECT
    -- Identifiers
    p.person_id,
    p.household_id,
               
    -- Demographics
    p.Age                         AS age,
    p.Sex                         AS sex,
    p.Marital_Status              AS marital_status,
               
    -- Education & skills         
    p.General_Education_Level     AS general_education_level,
    p.Technical_Education_Level   AS technical_education_level,
    p.Years_Formal_Education      AS years_formal_education,
    p.Vocational_Training         AS vocational_training,
    
    -- Employment status
            
    p.CWS_Status_Code             AS cws_status_code,
    p.Principal_Status_Code       AS principal_status_code,
    p.Subsidiary_Status_Code      AS subsidiary_status_code,
               
    -- Industry & occupation
    p.Principal_Industry_Code     AS principal_industry_code,
    p.Principal_Occupation_Code   AS principal_occupation_code,
               
    -- Earnings
    p.CWS_Earnings_Salaried       AS earnings_salaried,
    p.CWS_Earnings_SelfEmployed   AS earnings_self_employed,
    CASE
        WHEN p.CWS_Earnings_Salaried > 0 THEN 'Salaried'
        WHEN p.CWS_Earnings_SelfEmployed > 0 THEN 'Self-employed'
        ELSE 'No earnings'
    END AS earnings_type,
                          
    -- Job intensity
    p.weekly_hours_worked,
    p.underemployed_flag,
               
    -- Household context
    h.Sector                      AS sector,
    h.State_Ut_Code               AS state_ut_code,
    h.District_Code               AS district_code,
    h.Social_Group                AS social_group,
    h.Religion                    AS religion,
    h.Monthly_Consumer_Expenditure AS monthly_consumer_expenditure,
    h.Household_Size              AS household_size,

    -- Per-capita economic measure 
    (h.Monthly_Consumer_Expenditure * 1.0 / h.Household_Size)
        AS per_capita_mce,
           
    -- Time
    p.Quarter                     AS quarter,
    p.Visit                       AS visit
FROM person_fact p
JOIN household_dim h
ON p.household_id = h.household_id
               
--  Working-age restriction
WHERE p.Age BETWEEN 15 AND 64 ;
""")

conn.commit()

## Employment Analytical Fact Table:
- The employment_analytical_fact table is a person-level analytical dataset that integrates individual employment outcomes with household demographic and economic context. It includes key variables such as age, education, employment status, earnings type, weekly hours worked, and underemployment indicators, along with household characteristics like sector and per-capita consumption. The table is restricted to the working-age population (15–64) to ensure methodological correctness and is designed to support robust labour-market analysis across demographic, geographic, and socio-economic dimensions.

In [71]:
pd.read_sql_query("""
SELECT COUNT(*) AS total_rows
FROM employment_analytical_fact;
""", conn)

   total_rows
0      288340

In [72]:
pd.read_sql_query("""
SELECT
    SUM(CASE WHEN age IS NULL THEN 1 ELSE 0 END) AS missing_age,
    SUM(CASE WHEN cws_status_code IS NULL THEN 1 ELSE 0 END) AS missing_status,
    SUM(CASE WHEN sector IS NULL THEN 1 ELSE 0 END) AS missing_sector
FROM employment_analytical_fact;
""", conn)

   missing_age  missing_status  missing_sector
0            0               0               0

In [73]:
pd.read_sql(" select * from employment_analytical_fact ",conn)

,person_id,household_id,age,sex,marital_status,general_education_level,technical_education_level,years_formal_education,vocational_training,cws_status_code,principal_status_code,subsidiary_status_code,principal_industry_code,principal_occupation_code,earnings_salaried,earnings_self_employed,earnings_type,Weekly_Hours_Worked,underemployed_flag,sector,state_ut_code,district_code,social_group,religion,monthly_consumer_expenditure,household_size,per_capita_mce,quarter,visit
0,1,1,42,1,2,7,1,8,6.0,11,11,51.0,1140.0,611.0,0,18250,Self-employed,47,0,1,29,19,3,1,19833,5,3966.6,Q6,V1
1,2,1,38,2,2,7,1,8,6.0,11,11,21.0,1412.0,612.0,0,4850,Self-employed,48,0,1,29,19,3,1,19833,5,3966.6,Q6,V1
2,3,1,18,2,1,10,1,12,6.0,91,91,NaN,NaN,NaN,0,0,No earnings,0,0,1,29,19,3,1,19833,5,3966.6,Q6,V1
3,4,1,16,2,1,8,1,11,6.0,91,91,NaN,NaN,NaN,0,0,No earnings,0,0,1,29,19,3,1,19833,5,3966.6,Q6,V1
4,6,2,46,1,2,1,1,0,6.0,11,11,NaN,1140.0,611.0,0,16500,Self-employed,48,0,1,29,19,3,1,21346,5,4269.2,Q6,V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288335,415541,101952,34,1,2,13,13,16,6.0,31,31,NaN,46102.0,122.0,34500,0,Salaried,50,0,2,28,3,3,1,12833,2,6416.5,Q4,V1
288336,415542,101952,28,2,2,12,1,15,6.0,92,92,NaN,NaN,NaN,0,0,No earnings,0,0,2,28,3,3,1,12833,2,6416.5,Q4,V1
288337,415544,101953,58,2,2,10,1,12,6.0,92,92,NaN,NaN,NaN,0,0,No earnings,0,0,2,28,3,3,1,14042,2,7021.0,Q4,V1
288338,415548,101957,58,1,2,13,1,17,1.0,31,31,NaN,49110.0,313.0,52500,0,Salaried,58,0,2,28,3,3,1,21667,2,10833.5,Q4,V1
288339,415549,101957,57,2,2,13,1,16,6.0,31,31,NaN,85211.0,233.0,25000,0,Salaried,62,0,2,28,3,3,1,21667,2,10833.5,Q4,V1

## ADD ANALYTICS-FRIENDLY DERIVED COLUMNS

## Employment flag (binary)

In [74]:
cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN employed_flag INTEGER;
""")
conn.commit()

In [75]:
cursor.execute("""
UPDATE employment_analytical_fact
SET employed_flag =
    CASE
        WHEN cws_status_code IN (11,12,21) THEN 1
        ELSE 0
    END;
""")

conn.commit()

# Youth flag

In [76]:
cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN youth_flag INTEGER;
""")

conn.commit()

In [77]:
cursor.execute("""
UPDATE employment_analytical_fact
SET youth_flag =
    CASE
        WHEN age BETWEEN 15 AND 29 THEN 1
        ELSE 0
    END;
""")

conn.commit()

In [78]:
pd.read_sql_query("""
SELECT *
FROM employment_analytical_fact
LIMIT 5;
""", conn)

,person_id,household_id,age,sex,marital_status,general_education_level,technical_education_level,years_formal_education,vocational_training,cws_status_code,principal_status_code,subsidiary_status_code,principal_industry_code,principal_occupation_code,earnings_salaried,earnings_self_employed,earnings_type,Weekly_Hours_Worked,underemployed_flag,sector,state_ut_code,district_code,social_group,religion,monthly_consumer_expenditure,household_size,per_capita_mce,quarter,visit,employed_flag,youth_flag
0,1,1,42,1,2,7,1,8,6.0,11,11,51.0,1140.0,611.0,0,18250,Self-employed,47,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,1,0
1,2,1,38,2,2,7,1,8,6.0,11,11,21.0,1412.0,612.0,0,4850,Self-employed,48,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,1,0
2,3,1,18,2,1,10,1,12,6.0,91,91,NaN,NaN,NaN,0,0,No earnings,0,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,0,1
3,4,1,16,2,1,8,1,11,6.0,91,91,NaN,NaN,NaN,0,0,No earnings,0,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,0,1
4,6,2,46,1,2,1,1,0,6.0,11,11,NaN,1140.0,611.0,0,16500,Self-employed,48,0,1,29,19,3,1,21346,5,4269.2,Q6,V1,1,0

# Human-readable labels

## Quarter

In [90]:
cursor = conn.cursor()

cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN calendar_quarter_num INTEGER;
""")

cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN calendar_quarter_label TEXT;
""")

conn.commit()

In [91]:
cursor.execute("""
UPDATE employment_analytical_fact
SET calendar_quarter_num =
    CASE
        WHEN CAST(SUBSTR(quarter, 2) AS INTEGER) % 4 = 0
        THEN 4
        ELSE CAST(SUBSTR(quarter, 2) AS INTEGER) % 4
    END;
""")

conn.commit()

In [92]:
cursor.execute("""
UPDATE employment_analytical_fact
SET calendar_quarter_label =
    'Q' || calendar_quarter_num;
""")

conn.commit()

## Gender

In [80]:
cursor.execute("""ALTER TABLE employment_analytical_fact
ADD COLUMN gender TEXT;""")

cursor.execute("""
UPDATE employment_analytical_fact
SET gender =
    CASE
        WHEN sex = 1 THEN 'Male'
        WHEN sex = 2 THEN 'Female'
        ELSE 'Other / Unknown'
    END;
""")

conn.commit()

## Sector (Rural / Urban)

In [81]:
cursor.execute("""ALTER TABLE employment_analytical_fact
ADD COLUMN sector_label TEXT;""")

cursor.execute("""
UPDATE employment_analytical_fact
SET sector_label =
    CASE
        WHEN sector = 1 THEN 'Rural'
        WHEN sector = 2 THEN 'Urban'
        ELSE 'Unknown'
    END;
""")

conn.commit()

## Employment status (CWS – simplified)

In [82]:
cursor.execute("""ALTER TABLE employment_analytical_fact
ADD COLUMN employment_status_label TEXT;""")

cursor.execute("""
UPDATE employment_analytical_fact
SET employment_status_label =
    CASE
        WHEN employed_flag = 1 THEN 'Employed'
        ELSE 'Not employed'
    END;
""")

conn.commit()

## Underemployement

In [83]:
cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN underemployment_label TEXT;""")

cursor.execute("""
UPDATE employment_analytical_fact
SET underemployment_label =
    CASE
        WHEN underemployed_flag = 1 THEN 'Underemployed'
        ELSE 'Adequately employed / Not applicable'
    END;

""")

conn.commit()

## Youth vs Adult

In [84]:
cursor.execute("""ALTER TABLE employment_analytical_fact
ADD COLUMN age_group_label TEXT;""")

cursor.execute("""
UPDATE employment_analytical_fact
SET age_group_label =
    CASE
        WHEN youth_flag = 1 THEN 'Youth (15–29)'
        ELSE 'Adult (30–64)'
    END;
""")
conn.commit()

## Education grouping

In [85]:
cursor.execute("""ALTER TABLE employment_analytical_fact
ADD COLUMN education_group_label TEXT;""")

cursor.execute("""
UPDATE employment_analytical_fact
SET education_group_label =
    CASE
        WHEN general_education_level IN (0,1,2) THEN 'Primary or less'
        WHEN general_education_level IN (3,4,5) THEN 'Secondary'
        WHEN general_education_level IN (6,7) THEN 'Higher Secondary'
        WHEN general_education_level >= 8 THEN 'Graduate & above'
        ELSE 'Unknown'
    END;""")
conn.commit()

## Social Group Label

In [ ]:
cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN social_group_label TEXT;
""")
cursor.execute("""UPDATE employment_analytical_fact
SET social_group_label =
    CASE
        WHEN social_group = 1 THEN 'ST'
        WHEN social_group = 2 THEN 'SC'
        WHEN social_group = 3 THEN 'OBC'
        WHEN social_group = 9 THEN 'Others'
        ELSE 'Unknown'
    END;
""")
conn.commit()

- Semantic Layer & Human-Readable Enhancements:
  - To improve interpretability and analytical usability, human-readable label columns were added for key demographic, social, employment, and job-quality variables while preserving original coded fields. Critical India-specific classifications such as social group (SC, ST, OBC, Others), gender, sector, age group, and employment status were mapped to intuitive labels. Survey quarters were standardized using numeric sequencing to ensure correct temporal ordering. These enhancements form a semantic layer that enables clear, policy-relevant analysis across SQL, Python, and BI dashboards.

In [97]:
pd.read_sql(" select * from  employment_analytical_fact ",conn)

,person_id,household_id,age,sex,marital_status,general_education_level,technical_education_level,years_formal_education,vocational_training,cws_status_code,principal_status_code,subsidiary_status_code,principal_industry_code,principal_occupation_code,earnings_salaried,earnings_self_employed,earnings_type,Weekly_Hours_Worked,underemployed_flag,sector,state_ut_code,district_code,social_group,religion,monthly_consumer_expenditure,household_size,per_capita_mce,quarter,visit,employed_flag,youth_flag,gender,sector_label,employment_status_label,underemployment_label,age_group_label,education_group_label,calendar_quarter_num,calendar_quarter_label
0,1,1,42,1,2,7,1,8,6.0,11,11,51.0,1140.0,611.0,0,18250,Self-employed,47,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,1,0,Male,Rural,Employed,Adequately employed / Not applicable,Adult (30–64),Higher Secondary,2,Q2
1,2,1,38,2,2,7,1,8,6.0,11,11,21.0,1412.0,612.0,0,4850,Self-employed,48,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,1,0,Female,Rural,Employed,Adequately employed / Not applicable,Adult (30–64),Higher Secondary,2,Q2
2,3,1,18,2,1,10,1,12,6.0,91,91,NaN,NaN,NaN,0,0,No earnings,0,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,0,1,Female,Rural,Not employed,Adequately employed / Not applicable,Youth (15–29),Graduate & above,2,Q2
3,4,1,16,2,1,8,1,11,6.0,91,91,NaN,NaN,NaN,0,0,No earnings,0,0,1,29,19,3,1,19833,5,3966.6,Q6,V1,0,1,Female,Rural,Not employed,Adequately employed / Not applicable,Youth (15–29),Graduate & above,2,Q2
4,6,2,46,1,2,1,1,0,6.0,11,11,NaN,1140.0,611.0,0,16500,Self-employed,48,0,1,29,19,3,1,21346,5,4269.2,Q6,V1,1,0,Male,Rural,Employed,Adequately employed / Not applicable,Adult (30–64),Primary or less,2,Q2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288335,415541,101952,34,1,2,13,13,16,6.0,31,31,NaN,46102.0,122.0,34500,0,Salaried,50,0,2,28,3,3,1,12833,2,6416.5,Q4,V1,0,0,Male,Urban,Not employed,Adequately employed / Not applicable,Adult (30–64),Graduate & above,4,Q4
288336,415542,101952,28,2,2,12,1,15,6.0,92,92,NaN,NaN,NaN,0,0,No earnings,0,0,2,28,3,3,1,12833,2,6416.5,Q4,V1,0,1,Female,Urban,Not employed,Adequately employed / Not applicable,Youth (15–29),Graduate & above,4,Q4
288337,415544,101953,58,2,2,10,1,12,6.0,92,92,NaN,NaN,NaN,0,0,No earnings,0,0,2,28,3,3,1,14042,2,7021.0,Q4,V1,0,0,Female,Urban,Not employed,Adequately employed / Not applicable,Adult (30–64),Graduate & above,4,Q4
288338,415548,101957,58,1,2,13,1,17,1.0,31,31,NaN,49110.0,313.0,52500,0,Salaried,58,0,2,28,3,3,1,21667,2,10833.5,Q4,V1,0,0,Male,Urban,Not employed,Adequately employed / Not applicable,Adult (30–64),Graduate & above,4,Q4
288339,415549,101957,57,2,2,13,1,16,6.0,31,31,NaN,85211.0,233.0,25000,0,Salaried,62,0,2,28,3,3,1,21667,2,10833.5,Q4,V1,0,0,Female,Urban,Not employed,Adequately employed / Not applicable,Adult (30–64),Graduate & above,4,Q4

In [ ]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)

                         name
0                   household
1                      person
2               household_dim
3                 person_fact
4  employment_analytical_fact

In [113]:
cursor = conn.cursor()
cursor.execute("""CREATE TABLE employment_insights_fact AS
SELECT
    person_id,
    household_id,
    age,
    age_group_label,
    gender,
    sector_label,
    social_group_label,
    religion,
    education_group_label,
    employment_status_label,
    employed_flag,
    weekly_hours_worked,
    underemployed_flag,
    underemployment_label,
    earnings_type,
    earnings_salaried,
    earnings_self_employed,
    per_capita_mce,
    household_size,
    calendar_quarter_num,
    calendar_quarter_label
FROM employment_analytical_fact;""")
conn.commit()

In [111]:
pd.read_sql_query("PRAGMA table_info (employment_analytical_fact)",conn)

    cid                          name     type  notnull dflt_value  pk
0     0                     person_id                 0       None   0
1     1                  household_id                 0       None   0
2     2                           age      INT        0       None   0
3     3                           sex      INT        0       None   0
4     4                marital_status      INT        0       None   0
5     5       general_education_level      INT        0       None   0
6     6     technical_education_level      INT        0       None   0
7     7        years_formal_education      INT        0       None   0
8     8           vocational_training     REAL        0       None   0
9     9               cws_status_code      INT        0       None   0
10   10         principal_status_code      INT        0       None   0
11   11        subsidiary_status_code     REAL        0       None   0
12   12       principal_industry_code     REAL        0       None   0
13   13     principal_occupation_code     REAL        0       None   0
14   14             earnings_salaried      INT        0       None   0
15   15        earnings_self_employed      INT        0       None   0
16   16                 earnings_type                 0       None   0
17   17           Weekly_Hours_Worked                 0       None   0
18   18            underemployed_flag      INT        0       None   0
19   19                        sector      INT        0       None   0
20   20                 state_ut_code      INT        0       None   0
21   21                 district_code      INT        0       None   0
22   22                  social_group      INT        0       None   0
23   23                      religion      INT        0       None   0
24   24  monthly_consumer_expenditure      INT        0       None   0
25   25                household_size      INT        0       None   0
26   26                per_capita_mce                 0       None   0
27   27                       quarter     TEXT        0       None   0
28   28                         visit     TEXT        0       None   0
29   29                 employed_flag  INTEGER        0       None   0
30   30                    youth_flag  INTEGER        0       None   0
31   31                        gender     TEXT        0       None   0
32   32                  sector_label     TEXT        0       None   0
33   33       employment_status_label     TEXT        0       None   0
34   34         underemployment_label     TEXT        0       None   0
35   35               age_group_label     TEXT        0       None   0
36   36         education_group_label     TEXT        0       None   0
37   37          calendar_quarter_num  INTEGER        0       None   0
38   38        calendar_quarter_label     TEXT        0       None   0
39   39            social_group_label     TEXT        0       None   0

In [109]:
cursor = conn.cursor()

cursor.execute("""
ALTER TABLE employment_analytical_fact
ADD COLUMN social_group_label TEXT;
""")

conn.commit()

In [110]:
cursor.execute("""
UPDATE employment_analytical_fact
SET social_group_label =
    CASE
        WHEN social_group = 1 THEN 'ST'
        WHEN social_group = 2 THEN 'SC'
        WHEN social_group = 3 THEN 'OBC'
        WHEN social_group = 9 THEN 'Others'
        ELSE 'Unknown'
    END;
""")

conn.commit()

In [114]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)

                         name
0                   household
1                      person
2               household_dim
3                 person_fact
4  employment_analytical_fact
5    employment_insights_fact

In [116]:
pd.read_sql_query(" Select * from employment_insights_fact",conn)

,person_id,household_id,age,age_group_label,gender,sector_label,social_group_label,religion,education_group_label,employment_status_label,employed_flag,Weekly_Hours_Worked,underemployed_flag,underemployment_label,earnings_type,earnings_salaried,earnings_self_employed,per_capita_mce,household_size,calendar_quarter_num,calendar_quarter_label
0,1,1,42,Adult (30–64),Male,Rural,OBC,1,Higher Secondary,Employed,1,47,0,Adequately employed / Not applicable,Self-employed,0,18250,3966.6,5,2,Q2
1,2,1,38,Adult (30–64),Female,Rural,OBC,1,Higher Secondary,Employed,1,48,0,Adequately employed / Not applicable,Self-employed,0,4850,3966.6,5,2,Q2
2,3,1,18,Youth (15–29),Female,Rural,OBC,1,Graduate & above,Not employed,0,0,0,Adequately employed / Not applicable,No earnings,0,0,3966.6,5,2,Q2
3,4,1,16,Youth (15–29),Female,Rural,OBC,1,Graduate & above,Not employed,0,0,0,Adequately employed / Not applicable,No earnings,0,0,3966.6,5,2,Q2
4,6,2,46,Adult (30–64),Male,Rural,OBC,1,Primary or less,Employed,1,48,0,Adequately employed / Not applicable,Self-employed,0,16500,4269.2,5,2,Q2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288335,415541,101952,34,Adult (30–64),Male,Urban,OBC,1,Graduate & above,Not employed,0,50,0,Adequately employed / Not applicable,Salaried,34500,0,6416.5,2,4,Q4
288336,415542,101952,28,Youth (15–29),Female,Urban,OBC,1,Graduate & above,Not employed,0,0,0,Adequately employed / Not applicable,No earnings,0,0,6416.5,2,4,Q4
288337,415544,101953,58,Adult (30–64),Female,Urban,OBC,1,Graduate & above,Not employed,0,0,0,Adequately employed / Not applicable,No earnings,0,0,7021.0,2,4,Q4
288338,415548,101957,58,Adult (30–64),Male,Urban,OBC,1,Graduate & above,Not employed,0,58,0,Adequately employed / Not applicable,Salaried,52500,0,10833.5,2,4,Q4
288339,415549,101957,57,Adult (30–64),Female,Urban,OBC,1,Graduate & above,Not employed,0,62,0,Adequately employed / Not applicable,Salaried,25000,0,10833.5,2,4,Q4